window.GAME_DATA = {
 "areas": [
  {
   "area_id": "A01",
   "area_name_en": "Waikiki",
   "area_name_ja": "ワイキキ",
   "map_image": "waikiki_map.png",
   "description_ja": "ハワイ・オアフ島の海辺の街。低難易度の入門エリア。"
  }
 ],
 "scenes": [
  {
   "scene_id": "S01",
   "area_id": "A01",
   "title_en": "ABC Store",
   "title_ja": "ABCストア",
   "summary_en": "Shop at the convenience store — ask prices and find items.",
   "summary_mj": "コンビニで買い物。値段きく 商品さがす。",
   "difficulty_star": 1,
   "cefr": "A1",
   "pin_x": 34,
   "pin_y": 50,
   "display_order": 1
  },
  {
   "scene_id": "S02",
   "area_id": "A01",
   "title_en": "Waikiki Beach",
   "title_ja": "ワイキキビーチ",
   "summary_en": "At the beach — rent a chair, ask for a photo... or a funny tan.",
   "summary_mj": "ビーチで。チェア借りる 写真たのむ…おかしな日焼けも。",
   "difficulty_star": 1,
   "cefr": "A1",
   "pin_x": 50,
   "pin_y": 83,
   "display_order": 2
  },
  {
   "scene_id": "S03",
   "area_id": "A01",
   "title_en": "Garlic Shrimp Truck",
   "title_ja": "ガーリックシュリンプの屋台",
   "summary_en": "Order at the famous food truck and ask what's good.",
   "summary_mj": "名物フードトラックで注文。おすすめきく。",
   "difficulty_star": 1.5,
   "cefr": "A2",
   "pin_x": 58,
   "pin_y": 48,
   "display_order": 3
  },
  {
   "scene_id": "S04",
   "area_id": "A01",
   "title_en": "Street Directions",
   "title_ja": "街で道案内",
   "summary_en": "Find your way around town — beaches, bus stops, restrooms.",
   "summary_mj": "街で道さがす。ビーチ バス停 トイレ。",
   "difficulty_star": 1.5,
   "cefr": "A2",
   "pin_x": 42,
   "pin_y": 58,
   "display_order": 4
  },
  {
   "scene_id": "S05",
   "area_id": "A01",
   "title_en": "Diamond Head",
   "title_ja": "ダイヤモンドヘッド",
   "summary_en": "On the trail and at the summit — even a proposal?!",
   "summary_mj": "登山道と頂上で。プロポーズも!?",
   "difficulty_star": 2,
   "cefr": "B1",
   "pin_x": 85,
   "pin_y": 24,
   "display_order": 5
  },
  {
   "scene_id": "S06",
   "area_id": "A01",
   "title_en": "Beachside Restaurant",
   "title_ja": "海辺のレストラン",
   "summary_en": "A grown-up dinner — reservations and recommendations.",
   "summary_mj": "大人なディナー。予約 おすすめ。",
   "difficulty_star": 2.5,
   "cefr": "B2",
   "pin_x": 68,
   "pin_y": 60,
   "display_order": 6
  },
  {
   "scene_id": "S07",
   "area_id": "A01",
   "title_en": "Hotel Front Desk",
   "title_ja": "ホテルのフロント",
   "summary_en": "At the hotel front desk — late checkout and little troubles.",
   "summary_mj": "ホテルのフロントで。レイトチェックアウト 小さなトラブル。",
   "difficulty_star": 3,
   "cefr": "C1-C2",
   "pin_x": 41,
   "pin_y": 73,
   "display_order": 7
  }
 ],
 "variants": [
  {
   "scene_id": "S01",
   "variant_id": 1,
   "image": "S01_V1.png",
   "situation_ja": "商品を探す"
  },
  {
   "scene_id": "S01",
   "variant_id": 2,
   "image": "S01_V2.png",
   "situation_ja": "値段をたずねる"
  },
  {
   "scene_id": "S01",
   "variant_id": 3,
   "image": "S01_V3.png",
   "situation_ja": "お菓子を買いすぎる"
  },
  {
   "scene_id": "S02",
   "variant_id": 1,
   "image": "S02_V1.png",
   "situation_ja": "チェアを借りる"
  },
  {
   "scene_id": "S02",
   "variant_id": 2,
   "image": "S02_V2.png",
   "situation_ja": "写真をたのむ"
  },
  {
   "scene_id": "S02",
   "variant_id": 3,
   "image": "S02_V3.png",
   "situation_ja": "サングラス日焼け"
  },
  {
   "scene_id": "S03",
   "variant_id": 1,
   "image": "S03_V1.png",
   "situation_ja": "注文する"
  },
  {
   "scene_id": "S03",
   "variant_id": 2,
   "image": "S03_V2.png",
   "situation_ja": "おすすめを聞く"
  },
  {
   "scene_id": "S03",
   "variant_id": 3,
   "image": "S03_V3.png",
   "situation_ja": "ニンニクの息"
  },
  {
   "scene_id": "S04",
   "variant_id": 1,
   "image": "S04_V1.png",
   "situation_ja": "ビーチへの道"
  },
  {
   "scene_id": "S04",
   "variant_id": 2,
   "image": "S04_V2.png",
   "situation_ja": "バス停をさがす"
  },
  {
   "scene_id": "S04",
   "variant_id": 3,
   "image": "S04_V3.png",
   "situation_ja": "緊急トイレ"
  },
  {
   "scene_id": "S05",
   "variant_id": 1,
   "image": "S05_V1.png",
   "situation_ja": "プロポーズ"
  },
  {
   "scene_id": "S05",
   "variant_id": 2,
   "image": "S05_V2.png",
   "situation_ja": "登山の疲れ"
  },
  {
   "scene_id": "S05",
   "variant_id": 3,
   "image": "S05_V3.png",
   "situation_ja": "絶景で写真"
  },
  {
   "scene_id": "S06",
   "variant_id": 1,
   "image": "S06_V1.png",
   "situation_ja": "予約を確認"
  },
  {
   "scene_id": "S06",
   "variant_id": 2,
   "image": "S06_V2.png",
   "situation_ja": "辛さを相談"
  },
  {
   "scene_id": "S06",
   "variant_id": 3,
   "image": "S06_V3.png",
   "situation_ja": "財布を忘れた"
  },
  {
   "scene_id": "S07",
   "variant_id": 1,
   "image": "S07_V1.png",
   "situation_ja": "レイトチェックアウト"
  },
  {
   "scene_id": "S07",
   "variant_id": 2,
   "image": "S07_V2.png",
   "situation_ja": "エアコンの苦情"
  },
  {
   "scene_id": "S07",
   "variant_id": 3,
   "image": "S07_V3.png",
   "situation_ja": "タオルで締め出し"
  }
 ],
 "phrases": [
  {
   "id": "S01_V1_Q",
   "scene_id": "S01",
   "variant_id": 1,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "Where can I find sunscreen?",
   "chunks_en": "Where can I find / sunscreen?",
   "manjiro_ja": "どこ できる 私 見つける　日焼け止め？",
   "audio_file": "S01_V1_Q.wav",
   "explanation_en": "The classic way to ask where something is in a store. Swap 'sunscreen' for 'a charger' or 'the restroom'.",
   "explanation_mj": "店で物の場所きく定番。sunscreen を a charger / the restroom に変えて。"
  },
  {
   "id": "S01_V1_A",
   "scene_id": "S01",
   "variant_id": 1,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "It's next to the register.",
   "chunks_en": "It's / next to the register.",
   "manjiro_ja": "それ です　隣 レジ。",
   "audio_file": "S01_V1_A.wav",
   "explanation_en": "How to point someone to a spot. Change 'next to the register' to 'near the door'.",
   "explanation_mj": "場所を教える形。next to the register を near the door に。"
  },
  {
   "id": "S01_V2_Q",
   "scene_id": "S01",
   "variant_id": 2,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "How much is this?",
   "chunks_en": "How much / is this?",
   "manjiro_ja": "いくら　です これ？",
   "audio_file": "S01_V2_Q.wav",
   "explanation_en": "The must-know phrase for prices. Just switch 'this' to 'these' or 'that'.",
   "explanation_mj": "値段きく必須。this を these / that に変えるだけ。"
  },
  {
   "id": "S01_V2_A",
   "scene_id": "S01",
   "variant_id": 2,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "It's nine dollars.",
   "chunks_en": "It's / nine dollars.",
   "manjiro_ja": "それ です　9ドル。",
   "audio_file": "S01_V2_A.wav",
   "explanation_en": "The basic way to give a price. Just swap the number.",
   "explanation_mj": "値段を答える基本。数字を入れ替えるだけ。"
  },
  {
   "id": "S01_V3_Q",
   "scene_id": "S01",
   "variant_id": 3,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "Do you have a bigger basket?",
   "chunks_en": "Do you have / a bigger basket?",
   "manjiro_ja": "あなた 持つ　もっと大きい カゴ？",
   "audio_file": "S01_V3_Q.wav",
   "explanation_en": "The 'do you have a bigger ___?' pattern. Try 'a smaller size' too.",
   "explanation_mj": "「もっと大きい〜ある?」の型。a smaller size でも。"
  },
  {
   "id": "S01_V3_A",
   "scene_id": "S01",
   "variant_id": 3,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "You really love snacks, huh?",
   "chunks_en": "You really love snacks, / huh?",
   "manjiro_ja": "あなた 本当に 大好き お菓子　ね？",
   "audio_file": "S01_V3_A.wav",
   "explanation_en": "A friendly little tease. 'huh?' tags '..., right?' onto anything.",
   "explanation_mj": "親しみの一言。huh? は「〜だよね?」の万能タグ。"
  },
  {
   "id": "S02_V1_Q",
   "scene_id": "S02",
   "variant_id": 1,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "Can I rent a beach chair?",
   "chunks_en": "Can I rent / a beach chair?",
   "manjiro_ja": "できる 私 借りる　ビーチチェア？",
   "audio_file": "S02_V1_Q.wav",
   "explanation_en": "Asking to rent something. Swap 'a beach chair' for 'an umbrella' or 'a surfboard'.",
   "explanation_mj": "レンタル頼む定番。a beach chair を an umbrella / a surfboard に。"
  },
  {
   "id": "S02_V1_A",
   "scene_id": "S02",
   "variant_id": 1,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Sure, it's ten dollars an hour.",
   "chunks_en": "Sure, / it's ten dollars / an hour.",
   "manjiro_ja": "もちろん　それ です 10ドル　1時間。",
   "audio_file": "S02_V1_A.wav",
   "explanation_en": "Giving a rate. Change 'an hour' to 'a day' for daily rentals.",
   "explanation_mj": "料金を伝える形。an hour を a day に。"
  },
  {
   "id": "S02_V2_Q",
   "scene_id": "S02",
   "variant_id": 2,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "Could you take our photo?",
   "chunks_en": "Could you take / our photo?",
   "manjiro_ja": "もらえますか 撮る　私たちの 写真？",
   "audio_file": "S02_V2_Q.wav",
   "explanation_en": "The rock-solid way to ask for a photo. Switch 'our' and 'a' as needed.",
   "explanation_mj": "写真頼む鉄板。our / a を使い分けて。"
  },
  {
   "id": "S02_V2_A",
   "scene_id": "S02",
   "variant_id": 2,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Of course! Say cheese.",
   "chunks_en": "Of course! / Say cheese.",
   "manjiro_ja": "もちろん！　言う チーズ。",
   "audio_file": "S02_V2_A.wav",
   "explanation_en": "A cheerful yes plus the photo cue. Keep 'Say cheese' as a set phrase.",
   "explanation_mj": "快諾＋撮影のかけ声。Say cheese はそのまま。"
  },
  {
   "id": "S02_V3_Q",
   "scene_id": "S02",
   "variant_id": 3,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "I got a sunglasses tan!",
   "chunks_en": "I got / a sunglasses tan!",
   "manjiro_ja": "私 なった　サングラス 日焼け！",
   "audio_file": "S02_V3_Q.wav",
   "explanation_en": "A playful 'I got a ___ tan!' Change the word before 'tan'.",
   "explanation_mj": "「〜に日焼けした!」のネタ。tan の前を変えて。"
  },
  {
   "id": "S02_V3_A",
   "scene_id": "S02",
   "variant_id": 3,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Haha, you look like a panda!",
   "chunks_en": "Haha, / you look like a panda!",
   "manjiro_ja": "はは　あなた みたい パンダ！",
   "audio_file": "S02_V3_A.wav",
   "explanation_en": "Teasing someone's look. 'you look like ___' works anywhere.",
   "explanation_mj": "見た目いじる軽口。you look like ◯◯ は使い回せる。"
  },
  {
   "id": "S03_V1_Q",
   "scene_id": "S03",
   "variant_id": 1,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "Can I get the garlic shrimp plate?",
   "chunks_en": "Can I get / the garlic shrimp plate?",
   "manjiro_ja": "できる 私 もらう　ガーリックシュリンプ プレート？",
   "audio_file": "S03_V1_Q.wav",
   "explanation_en": "The all-purpose way to order. Put any dish in 'the ___ plate'.",
   "explanation_mj": "注文の万能形。the 〜 plate に料理名を。"
  },
  {
   "id": "S03_V1_A",
   "scene_id": "S03",
   "variant_id": 1,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Sure, do you want extra rice?",
   "chunks_en": "Sure, / do you want / extra rice?",
   "manjiro_ja": "もちろん　あなた 欲しい　追加 ライス？",
   "audio_file": "S03_V1_A.wav",
   "explanation_en": "Offering an add-on. Swap 'extra rice' for 'more sauce'.",
   "explanation_mj": "追加を勧める形。extra rice を more sauce に。"
  },
  {
   "id": "S03_V2_Q",
   "scene_id": "S03",
   "variant_id": 2,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "What do you recommend here?",
   "chunks_en": "What do you recommend / here?",
   "manjiro_ja": "何 あなた おすすめ　ここで？",
   "audio_file": "S03_V2_Q.wav",
   "explanation_en": "A handy way to ask for suggestions. Change 'here' to 'for dessert'.",
   "explanation_mj": "おすすめきく便利形。here を for dessert に。"
  },
  {
   "id": "S03_V2_A",
   "scene_id": "S03",
   "variant_id": 2,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "The garlic shrimp is our most popular.",
   "chunks_en": "The garlic shrimp / is our most popular.",
   "manjiro_ja": "ガーリックシュリンプ　です 私たちの 一番 人気。",
   "audio_file": "S03_V2_A.wav",
   "explanation_en": "Pitching the top pick. Just swap the dish name.",
   "explanation_mj": "一押しを伝える形。料理名を差し替え。"
  },
  {
   "id": "S03_V3_Q",
   "scene_id": "S03",
   "variant_id": 3,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "It's delicious, but my breath smells now!",
   "chunks_en": "It's delicious, / but my breath / smells now!",
   "manjiro_ja": "それ です 美味しい　でも 私の 息　くさい 今！",
   "audio_file": "S03_V3_Q.wav",
   "explanation_en": "The 'it's great, but ___' punchline. Change what comes after 'but'.",
   "explanation_mj": "「美味しいけど〜」の落ち。but の後を変えて。"
  },
  {
   "id": "S03_V3_A",
   "scene_id": "S03",
   "variant_id": 3,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Here, have a free mint.",
   "chunks_en": "Here, / have a free mint.",
   "manjiro_ja": "どうぞ　取る 無料 ミント。",
   "audio_file": "S03_V3_A.wav",
   "explanation_en": "Offering something. Swap 'a free mint' for 'a napkin'.",
   "explanation_mj": "物を差し出す一言。a free mint を a napkin に。"
  },
  {
   "id": "S04_V1_Q",
   "scene_id": "S04",
   "variant_id": 1,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "How do I get to the beach?",
   "chunks_en": "How do I get / to the beach?",
   "manjiro_ja": "どうやって 私 行く　へ ビーチ？",
   "audio_file": "S04_V1_Q.wav",
   "explanation_en": "The key phrase for directions. Change 'the beach' to 'the station'.",
   "explanation_mj": "道きく最重要。the beach を the station に。"
  },
  {
   "id": "S04_V1_A",
   "scene_id": "S04",
   "variant_id": 1,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Go straight and turn left.",
   "chunks_en": "Go straight / and turn left.",
   "manjiro_ja": "行く まっすぐ　そして 曲がる 左。",
   "audio_file": "S04_V1_A.wav",
   "explanation_en": "Basic directions. Mix and match 'straight', 'left', 'right'.",
   "explanation_mj": "道案内の基本。straight / left / right を組み替えて。"
  },
  {
   "id": "S04_V2_Q",
   "scene_id": "S04",
   "variant_id": 2,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "Where is the nearest bus stop?",
   "chunks_en": "Where is / the nearest bus stop?",
   "manjiro_ja": "どこ です　一番近い バス停？",
   "audio_file": "S04_V2_Q.wav",
   "explanation_en": "The 'where's the nearest ___?' pattern. Try 'ATM' or 'pharmacy'.",
   "explanation_mj": "「一番近い〜どこ?」。bus stop を ATM / pharmacy に。"
  },
  {
   "id": "S04_V2_A",
   "scene_id": "S04",
   "variant_id": 2,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "It's just around the corner.",
   "chunks_en": "It's just / around the corner.",
   "manjiro_ja": "それ です ちょうど　回って 角。",
   "audio_file": "S04_V2_A.wav",
   "explanation_en": "A go-to for 'it's right there'. 'around the corner' is super handy.",
   "explanation_mj": "「すぐそこ」の定番。around the corner が便利。"
  },
  {
   "id": "S04_V3_Q",
   "scene_id": "S04",
   "variant_id": 3,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "Where's the restroom? It's urgent!",
   "chunks_en": "Where's the restroom? / It's urgent!",
   "manjiro_ja": "どこ です トイレ？　それ です 緊急！",
   "audio_file": "S04_V3_Q.wav",
   "explanation_en": "An emergency essential. 'It's urgent!' adds the pressure.",
   "explanation_mj": "緊急時の必須。It's urgent! で切迫感を。"
  },
  {
   "id": "S04_V3_A",
   "scene_id": "S04",
   "variant_id": 3,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Run! It's behind that store!",
   "chunks_en": "Run! / It's behind that store!",
   "manjiro_ja": "走る！　それ です 後ろ あの 店！",
   "audio_file": "S04_V3_A.wav",
   "explanation_en": "Quick directions in a pinch. Change 'behind that store' to 'across the street'.",
   "explanation_mj": "とっさの案内。behind that store を across the street に。"
  },
  {
   "id": "S05_V1_Q",
   "scene_id": "S05",
   "variant_id": 1,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "Will you marry me, here at the top?",
   "chunks_en": "Will you marry me, / here at the top?",
   "manjiro_ja": "だろう あなた 結婚する 私　ここ 頂上で？",
   "audio_file": "S05_V1_Q.wav",
   "explanation_en": "A grand proposal line. Swap the place after 'here at' — if the moment ever comes.",
   "explanation_mj": "プロポーズの王道。here at の場所を変えて…機会があれば。"
  },
  {
   "id": "S05_V1_A",
   "scene_id": "S05",
   "variant_id": 1,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Yes! This view makes it perfect.",
   "chunks_en": "Yes! / This view / makes it perfect.",
   "manjiro_ja": "はい！　この 景色　する それ 完璧。",
   "audio_file": "S05_V1_A.wav",
   "explanation_en": "'___ makes it perfect.' Change 'This view' to 'Your smile'.",
   "explanation_mj": "「〜が完璧にする」。This view を Your smile に。"
  },
  {
   "id": "S05_V2_Q",
   "scene_id": "S05",
   "variant_id": 2,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "How much farther to the summit?",
   "chunks_en": "How much farther / to the summit?",
   "manjiro_ja": "あと どれくらい　へ 頂上？",
   "audio_file": "S05_V2_Q.wav",
   "explanation_en": "The 'how much farther?' line. Swap 'the summit' for 'the top' or 'the exit'.",
   "explanation_mj": "「あとどれくらい?」。the summit を the top / the exit に。"
  },
  {
   "id": "S05_V2_A",
   "scene_id": "S05",
   "variant_id": 2,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Almost there — just ten more minutes.",
   "chunks_en": "Almost there / — just ten more minutes.",
   "manjiro_ja": "ほぼ そこ　ちょうど あと 10分。",
   "audio_file": "S05_V2_A.wav",
   "explanation_en": "A classic bit of encouragement. Just change the time.",
   "explanation_mj": "励ます定番。時間を入れ替えるだけ。"
  },
  {
   "id": "S05_V3_Q",
   "scene_id": "S05",
   "variant_id": 3,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "Could you take a photo with the ocean behind us?",
   "chunks_en": "Could you take a photo / with the ocean / behind us?",
   "manjiro_ja": "もらえますか 撮る 写真　と 海　後ろ 私たち？",
   "audio_file": "S05_V3_Q.wav",
   "explanation_en": "A photo request with a background. 'with ___ behind us' is handy.",
   "explanation_mj": "背景指定の写真依頼。with 〜 behind us が便利。"
  },
  {
   "id": "S05_V3_A",
   "scene_id": "S05",
   "variant_id": 3,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Sure, step a little closer together.",
   "chunks_en": "Sure, / step a little closer / together.",
   "manjiro_ja": "もちろん　寄る 少し 近く　一緒に。",
   "audio_file": "S05_V3_A.wav",
   "explanation_en": "Photo directions. Mix 'closer' and 'together'.",
   "explanation_mj": "撮影の指示。closer / together を組み替えて。"
  },
  {
   "id": "S06_V1_Q",
   "scene_id": "S06",
   "variant_id": 1,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "I'd like to confirm my reservation for two.",
   "chunks_en": "I'd like to confirm / my reservation / for two.",
   "manjiro_ja": "したい 確認　私の 予約　向け 2名。",
   "audio_file": "S06_V1_Q.wav",
   "explanation_en": "A polite way to confirm a booking. Just change the number in 'for two'.",
   "explanation_mj": "予約確認の丁寧形。for two の数字を変えて。"
  },
  {
   "id": "S06_V1_A",
   "scene_id": "S06",
   "variant_id": 1,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Of course, your table is ready by the window.",
   "chunks_en": "Of course, / your table is ready / by the window.",
   "manjiro_ja": "もちろん　あなたの テーブル です 準備できた　そば 窓。",
   "audio_file": "S06_V1_A.wav",
   "explanation_en": "Showing someone in. Swap 'by the window' for 'on the terrace'.",
   "explanation_mj": "案内の言い方。by the window を on the terrace に。"
  },
  {
   "id": "S06_V2_Q",
   "scene_id": "S06",
   "variant_id": 2,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "Could you recommend something that isn't too spicy?",
   "chunks_en": "Could you recommend / something / that isn't too spicy?",
   "manjiro_ja": "もらえますか おすすめ　何か　ない 辛すぎ？",
   "audio_file": "S06_V2_Q.wav",
   "explanation_en": "A conditional recommendation request. Change 'isn't too spicy' to 'without nuts'.",
   "explanation_mj": "条件付きおすすめ依頼。isn't too spicy を without nuts に。"
  },
  {
   "id": "S06_V2_A",
   "scene_id": "S06",
   "variant_id": 2,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "The grilled mahi-mahi is mild and very fresh.",
   "chunks_en": "The grilled mahi-mahi / is mild / and very fresh.",
   "manjiro_ja": "グリルした マヒマヒ　です マイルド　そして とても 新鮮。",
   "audio_file": "S06_V2_A.wav",
   "explanation_en": "Recommending a dish. Swap the dish and the adjective.",
   "explanation_mj": "料理を勧める形。料理名と形容詞を差し替え。"
  },
  {
   "id": "S06_V3_Q",
   "scene_id": "S06",
   "variant_id": 3,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "This is embarrassing, but I left my wallet at the hotel.",
   "chunks_en": "This is embarrassing, / but I left my wallet / at the hotel.",
   "manjiro_ja": "これ です 恥ずかしい　でも 私 忘れた 私の 財布　に ホテル。",
   "audio_file": "S06_V3_Q.wav",
   "explanation_en": "An awkward-confession opener. 'This is embarrassing, but ___' is gold.",
   "explanation_mj": "気まずい告白の前置き。This is embarrassing, but 〜 が万能。"
  },
  {
   "id": "S06_V3_A",
   "scene_id": "S06",
   "variant_id": 3,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "No worries, we can hold your order until you're back.",
   "chunks_en": "No worries, / we can hold your order / until you're back.",
   "manjiro_ja": "心配ない　私たち できる キープ あなたの 注文　まで あなた 戻る。",
   "audio_file": "S06_V3_A.wav",
   "explanation_en": "A reassuring reply. 'No worries' puts people at ease.",
   "explanation_mj": "気遣いの返し。No worries で安心させる。"
  },
  {
   "id": "S07_V1_Q",
   "scene_id": "S07",
   "variant_id": 1,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "Would it be possible to arrange a late checkout tomorrow?",
   "chunks_en": "Would it be possible / to arrange a late checkout / tomorrow?",
   "manjiro_ja": "でしょうか それ 可能　手配する レイトチェックアウト　明日？",
   "audio_file": "S07_V1_Q.wav",
   "explanation_en": "Top-tier polite request. 'Would it be possible to ___' fits almost anything.",
   "explanation_mj": "丁寧依頼の最上級。Would it be possible to 〜 は何にでも。"
  },
  {
   "id": "S07_V1_A",
   "scene_id": "S07",
   "variant_id": 1,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "Certainly, we can extend it until two without any charge.",
   "chunks_en": "Certainly, / we can extend it until two / without any charge.",
   "manjiro_ja": "かしこまりました　私たち できる 延長する それ まで 2時　なし 料金。",
   "audio_file": "S07_V1_A.wav",
   "explanation_en": "A yes with conditions. Swap the time or the terms.",
   "explanation_mj": "快諾＋条件提示。時間や条件を差し替え。"
  },
  {
   "id": "S07_V2_Q",
   "scene_id": "S07",
   "variant_id": 2,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "I don't mean to complain, but the air conditioning isn't working.",
   "chunks_en": "I don't mean to complain, / but the air conditioning / isn't working.",
   "manjiro_ja": "私 ない つもり 文句　でも エアコン　ない 動く。",
   "audio_file": "S07_V2_Q.wav",
   "explanation_en": "A complaint without friction. 'I don't mean to complain, but ___' is handy.",
   "explanation_mj": "角を立てない苦情。I don't mean to complain, but 〜 が便利。"
  },
  {
   "id": "S07_V2_A",
   "scene_id": "S07",
   "variant_id": 2,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "I sincerely apologize; I'll send someone up right away.",
   "chunks_en": "I sincerely apologize; / I'll send someone up / right away.",
   "manjiro_ja": "私 心から お詫び　私 だろう 行かせる 誰か 上　すぐに。",
   "audio_file": "S07_V2_A.wav",
   "explanation_en": "A polite apology plus action. Works in business too.",
   "explanation_mj": "丁寧な謝罪＋対応。ビジネスでも使える。"
  },
  {
   "id": "S07_V3_Q",
   "scene_id": "S07",
   "variant_id": 3,
   "role": "questioner",
   "turn_order": 1,
   "text_en": "This may sound silly, but there's a giant gecko in my bathroom.",
   "chunks_en": "This may sound silly, / but there's a giant gecko / in my bathroom.",
   "manjiro_ja": "これ かも 聞こえる ばかげた　でも いる 大きな ヤモリ　に 私の バスルーム。",
   "audio_file": "S07_V3_Q.wav",
   "explanation_en": "A light way to report a surprise. 'This may sound silly, but ___' softens it.",
   "explanation_mj": "驚きを軽く伝える。This may sound silly, but 〜 で和らげる。"
  },
  {
   "id": "S07_V3_A",
   "scene_id": "S07",
   "variant_id": 3,
   "role": "answerer",
   "turn_order": 2,
   "text_en": "No worries, sir; I'll have someone gently move it outside.",
   "chunks_en": "No worries, sir; / I'll have someone / gently move it outside.",
   "manjiro_ja": "心配ない　私 だろう 頼む 誰か　そっと 動かす それ 外。",
   "audio_file": "S07_V3_A.wav",
   "explanation_en": "A calm, can-do response. 'No worries' plus a solution.",
   "explanation_mj": "落ち着いた対応。No worries ＋ 解決策。"
  }
 ],
 "lexicon": {
  "a": "ə",
  "air": "ɛr",
  "almost": "ˈɔlˌmoʊst",
  "an": "ən",
  "and": "ənd",
  "any": "ˈɛni",
  "apologize": "əˈpɑləˌʤaɪz",
  "around": "əraʊnd",
  "arrange": "əreɪnʤ",
  "at": "æt",
  "away": "əˈweɪ",
  "back": "bæk",
  "basket": "ˈbæskət",
  "bathroom": "ˈbæθˌrum",
  "be": "bi",
  "beach": "biʧ",
  "behind": "bɪˈhaɪnd",
  "bigger": "ˈbɪgər",
  "breath": "brɛθ",
  "bus": "bəs",
  "but": "bət",
  "by": "baɪ",
  "can": "kən",
  "certainly": "ˈsərtənli",
  "chair": "ʧɛr",
  "charge": "ʧɑrʤ",
  "checkout": "ˈʧɛˌkaʊt",
  "cheese": "ʧiz",
  "closer": "ˈkloʊzər",
  "complain": "kəmˈpleɪn",
  "conditioning": "kənˈdɪʃənɪŋ",
  "confirm": "kənˈfərm",
  "corner": "ˈkɔrnər",
  "could": "kʊd",
  "course": "kɔrs",
  "delicious": "dɪˈlɪʃəs",
  "do": "du",
  "dollars": "ˈdɔlərz",
  "don't": "doʊnt",
  "embarrassing": "ɪmˈbɛrəsɪŋ",
  "extend": "ɪkˈstɛnd",
  "extra": "ˈɛkstrə",
  "farther": "ˈfɑrðər",
  "find": "faɪnd",
  "for": "fər",
  "free": "fri",
  "fresh": "frɛʃ",
  "garlic": "ˈgɑrlɪk",
  "gecko": "ˈɡɛkoʊ",
  "gently": "ˈʤɛntli",
  "get": "gɪt",
  "giant": "ʤaɪənt",
  "go": "goʊ",
  "got": "gɑt",
  "grilled": "grɪld",
  "haha": "hɑˈhɑ",
  "have": "hæv",
  "here": "hir",
  "hold": "hoʊld",
  "hotel": "hoʊˈtɛl",
  "hour": "aʊər",
  "how": "haʊ",
  "huh": "hə",
  "i": "aɪ",
  "i'd": "aɪd",
  "i'll": "aɪl",
  "in": "ɪn",
  "is": "ɪz",
  "isn't": "ˈɪzənt",
  "it": "ɪt",
  "it's": "ɪts",
  "just": "ʤɪst",
  "late": "leɪt",
  "left": "lɛft",
  "like": "laɪk",
  "little": "ˈlɪtəl",
  "look": "lʊk",
  "love": "ləv",
  "mahi-mahi": "ˌmɑhiˈmɑhi",
  "makes": "meɪks",
  "marry": "ˈmɛri",
  "may": "meɪ",
  "me": "mi",
  "mean": "min",
  "mild": "maɪld",
  "mint": "mɪnt",
  "minutes": "ˈmɪnəts",
  "more": "mɔr",
  "most": "moʊst",
  "move": "muv",
  "much": "məʧ",
  "my": "maɪ",
  "nearest": "ˈnɪrəst",
  "next": "nɛkst",
  "nine": "naɪn",
  "no": "noʊ",
  "now": "naʊ",
  "ocean": "ˈoʊʃən",
  "of": "əv",
  "order": "ˈɔrdər",
  "our": "ɑr",
  "outside": "ˈaʊtˈsaɪd",
  "panda": "ˈpændə",
  "perfect": "ˈpərˌfɪkt",
  "photo": "ˈfoʊˌtoʊ",
  "plate": "pleɪt",
  "popular": "ˈpɑpjələr",
  "possible": "ˈpɑsəbəl",
  "ready": "ˈrɛdi",
  "really": "ˈrɪli",
  "recommend": "ˌrɛkəˈmɛnd",
  "register": "ˈrɛʤɪstər",
  "rent": "rɛnt",
  "reservation": "ˌrɛzərˈveɪʃən",
  "restroom": "ˈrɛˌstrum",
  "rice": "raɪs",
  "right": "raɪt",
  "run": "rən",
  "say": "seɪ",
  "send": "sɛnd",
  "shrimp": "ʃrɪmp",
  "silly": "ˈsɪli",
  "sincerely": "sɪnˈsɪrli",
  "sir": "sər",
  "smells": "smɛlz",
  "snacks": "snæks",
  "someone": "ˈsəmˌwən",
  "something": "ˈsəmθɪŋ",
  "sound": "saʊnd",
  "spicy": "ˈspaɪsi",
  "step": "stɛp",
  "stop": "stɑp",
  "store": "stɔr",
  "straight": "streɪt",
  "summit": "ˈsəmɪt",
  "sunglasses": "ˈsənˌglæsɪz",
  "sunscreen": "ˈsənskrin",
  "sure": "ʃʊr",
  "table": "ˈteɪbəl",
  "take": "teɪk",
  "tan": "tæn",
  "ten": "tɛn",
  "that": "ðət",
  "the": "ðə",
  "there": "ðɛr",
  "there's": "ðɛrz",
  "this": "ðɪs",
  "to": "tɪ",
  "together": "təˈgɛðər",
  "tomorrow": "təˈmɑˌroʊ",
  "too": "tu",
  "top": "tɔp",
  "turn": "tərn",
  "two": "tu",
  "until": "ənˈtɪl",
  "up": "əp",
  "urgent": "ˈərʤənt",
  "us": "ˈjuˈɛs",
  "very": "ˈvɛri",
  "view": "vju",
  "wallet": "ˈwɔlət",
  "want": "wɔnt",
  "we": "wi",
  "what": "wət",
  "where": "wɛr",
  "where's": "wɛrz",
  "will": "wɪl",
  "window": "ˈwɪndoʊ",
  "with": "wɪθ",
  "without": "wɪˈθaʊt",
  "working": "ˈwərkɪŋ",
  "worries": "ˈwəriz",
  "would": "wʊd",
  "yes": "jɛs",
  "you": "ju",
  "you're": "jʊr",
  "your": "jʊr"
 }
};
